[Variables]
;@About | Name About | Description News And Interests settings
;@Default | Name Settings | Icon [\xF8B0]
;?String | Name Scale | Description Change the overall size of the widgets
Scale=0
;?String | Name Draggable | Description Change this to 0 once you have the widgets in the perfect place
Draggable=1
;?String | Name High DPI | Description Change this to 1 if you are using Rainmeter on high DPI mode
HighDPI=0
;?String | Name Weather Unit | Description F for Fahrenheight and C for Celcius. Capitals please!
Unit=F
